### ISSUE TITLE
Implementation of Equation (7) , (8) and (11) from the paper

### ISSUE THREAD

**Issue by hmishfaq** [FlorenceFeng/ENIAC#2]
Where exactly in https://github.com/FlorenceFeng/ENIAC/blob/master/code/DeepRL/deep_rl/agent/RPG_agent.py are Equation (7) , (8) and (11) from the paper https://arxiv.org/pdf/2103.11559.pdf implemented?

**Comment by FlorenceFeng** [comment]
As mentioned in the Experiment section of the paper, we implement the actor-critic step following PPO and specifically, the code of Zhang 2018. You can find the update to the network in the function 

`step_optimize_policy()`

and the network structure can be found in 

https://github.com/FlorenceFeng/ENIAC/blob/master/code/DeepRL/deep_rl/network/network_heads.py

For MountainCar, we use ` GaussianActorCriticNet`.

The crucial part of the code is the policy cover and the width training. You can find them in RPG_agent.py at
`self.policy_mixture` and `width_loss(), retrain_width(), get_critic_width()`

Bonuses are added at Line 330-358 in RPG_agent.py.
