### ISSUE TITLE
running on combination lock

### ISSUE THREAD

**Issue by hmishfaq** [FlorenceFeng/ENIAC#3]
When I am running
`python -i run.py -alg ppo-rpg -bonus_coeff 5.0 -horizon 3 -env diabcombolockhallway -lr 0.0001 -seed 1 -bonus counts`

I am getting 
`File "/home/mila/i/ishfaqha/code/ENIAC/code/DeepRL/deep_rl/component/envs.py", line 203, in build_env_homer
    import homer_envs
ModuleNotFoundError: No module named 'homer_envs'`

Any suggestion on how to resolve it? 
I tried doing `python setup.py build` from `ENIAC/code/homer_envs` but it says
`running build
running build_py
file homer_envs.py (for module homer_envs) not found
file homer_envs.py (for module homer_envs) not found`

**Comment by hmishfaq** [comment]
I solved it moving [homer_env](https://github.com/FlorenceFeng/ENIAC/tree/master/code/homer_envs/homer_envs) under [DeepRL](https://github.com/FlorenceFeng/ENIAC/tree/master/code/DeepRL)

**Comment by FlorenceFeng** [comment]
great.
